import { z } from "zod";

import { prospectSchema } from "@/lib/validation";

export const mockProspects = z.array(prospectSchema).parse([
  {
    id: "prospect-clinica-dental-nova",
    businessName: "Clínica Dental Nova",
    niche: "Odontología",
    location: "Ciudad de Panamá, Panamá",
    websiteUrl: null,
    websiteStatus: "sin-sitio",
    publicEmail: "contacto@clinicadentalnova.example",
    publicPhone: "+507 6000-0101",
    publicWhatsapp: "+507 6000-0101",
    contactSourceUrl: "https://clinicadentalnova.example/perfil-publico",
    opportunityScore: 91,
    commercialStatus: "alta-prioridad",
    recommendedOffer:
      "Sitio web de servicios con reserva de citas y acceso a WhatsApp",
    aiSummary:
      "Clínica ficticia con buena reputación local y dependencia de redes sociales para captar pacientes.",
    detectedOpportunities: [
      "Crear un sitio indexable con servicios y especialistas",
      "Centralizar las reservas de citas",
      "Presentar reseñas y preguntas frecuentes",
    ],
    createdAt: "2026-07-08T14:00:00.000Z",
    updatedAt: "2026-07-18T15:30:00.000Z",
  },
  {
    id: "prospect-taller-automax",
    businessName: "Taller AutoMax",
    niche: "Taller automotriz",
    location: "David, Chiriquí",
    websiteUrl: "https://tallerautomax.example",
    websiteStatus: "desactualizado",
    publicEmail: "servicio@tallerautomax.example",
    publicPhone: "+507 6000-0102",
    publicWhatsapp: "+507 6000-0102",
    contactSourceUrl: "https://tallerautomax.example/contacto",
    opportunityScore: 87,
    commercialStatus: "propuesta-lista",
    recommendedOffer:
      "Renovación web con catálogo de servicios y solicitud de cotización",
    aiSummary:
      "Taller ficticio con un sitio antiguo que no comunica con claridad sus servicios ni facilita cotizaciones móviles.",
    detectedOpportunities: [
      "Actualizar la experiencia móvil",
      "Añadir solicitudes de cotización por tipo de servicio",
      "Destacar garantías y experiencia técnica",
    ],
    createdAt: "2026-07-09T16:15:00.000Z",
    updatedAt: "2026-07-18T18:10:00.000Z",
  },
  {
    id: "prospect-restaurante-la-toscana",
    businessName: "Restaurante La Toscana",
    niche: "Restaurante italiano",
    location: "La Chorrera, Panamá Oeste",
    websiteUrl: null,
    websiteStatus: "solo-redes",
    publicEmail: null,
    publicPhone: "+507 6000-0103",
    publicWhatsapp: "+507 6000-0103",
    contactSourceUrl: "https://latoscana.example/perfil-publico",
    opportunityScore: 84,
    commercialStatus: "respondio",
    recommendedOffer: "Sitio gastronómico con menú, reservas y ubicación",
    aiSummary:
      "Restaurante ficticio activo en redes, pero sin canal propio para mostrar el menú actualizado y gestionar reservas.",
    detectedOpportunities: [
      "Publicar un menú accesible y fácil de actualizar",
      "Habilitar reservas desde móvil",
      "Mejorar el posicionamiento para búsquedas locales",
    ],
    createdAt: "2026-07-10T13:20:00.000Z",
    updatedAt: "2026-07-19T00:05:00.000Z",
  },
  {
    id: "prospect-abogados-rivera",
    businessName: "Abogados Rivera",
    niche: "Servicios legales",
    location: "Bogotá, Colombia",
    websiteUrl: "https://abogadosrivera.example",
    websiteStatus: "desactualizado",
    publicEmail: "consultas@abogadosrivera.example",
    publicPhone: "+57 601 555 0104",
    publicWhatsapp: null,
    contactSourceUrl: "https://abogadosrivera.example/contacto",
    opportunityScore: 79,
    commercialStatus: "negociacion",
    recommendedOffer:
      "Sitio corporativo por áreas de práctica y formulario de consulta",
    aiSummary:
      "Firma ficticia con información profesional valiosa, presentada en un sitio con navegación y contenido desactualizados.",
    detectedOpportunities: [
      "Organizar servicios por áreas de práctica",
      "Mejorar confianza con perfiles del equipo",
      "Simplificar la solicitud de consultas",
    ],
    createdAt: "2026-07-11T17:45:00.000Z",
    updatedAt: "2026-07-17T20:00:00.000Z",
  },
  {
    id: "prospect-spa-aura",
    businessName: "Spa Aura",
    niche: "Bienestar y belleza",
    location: "San José, Costa Rica",
    websiteUrl: "https://spaaura.example",
    websiteStatus: "basico",
    publicEmail: "reservas@spaaura.example",
    publicPhone: "+506 4000-0105",
    publicWhatsapp: "+506 6000-0105",
    contactSourceUrl: "https://spaaura.example/reservas",
    opportunityScore: 76,
    commercialStatus: "ganado",
    recommendedOffer: "Rediseño orientado a reservas y paquetes de bienestar",
    aiSummary:
      "Spa ficticio con un sitio básico que describe servicios, pero no permite consultar disponibilidad ni reservar en línea.",
    detectedOpportunities: [
      "Incorporar reserva de horarios",
      "Agrupar servicios en paquetes",
      "Reforzar confianza con testimonios y políticas claras",
    ],
    createdAt: "2026-07-12T15:10:00.000Z",
    updatedAt: "2026-07-18T21:40:00.000Z",
  },
  {
    id: "prospect-inmobiliaria-central",
    businessName: "Inmobiliaria Central",
    niche: "Bienes raíces",
    location: "Ciudad de Panamá, Panamá",
    websiteUrl: "https://inmobiliariacentral.example",
    websiteStatus: "basico",
    publicEmail: "ventas@inmobiliariacentral.example",
    publicPhone: "+507 6000-0106",
    publicWhatsapp: null,
    contactSourceUrl: "https://inmobiliariacentral.example/contacto",
    opportunityScore: 74,
    commercialStatus: "analizando",
    recommendedOffer:
      "Catálogo inmobiliario con filtros y captación de interesados",
    aiSummary:
      "Inmobiliaria ficticia con catálogo limitado y sin herramientas claras para filtrar propiedades o registrar interesados.",
    detectedOpportunities: [
      "Añadir filtros por zona, precio y tipo",
      "Crear fichas completas de propiedades",
      "Capturar consultas asociadas a cada inmueble",
    ],
    createdAt: "2026-07-13T14:30:00.000Z",
    updatedAt: "2026-07-18T12:15:00.000Z",
  },
]);
